recommendations = [
  # nix
  "bbenoist.Nix",
  "jnoortheen.nix-ide",
  # dev
  "Codeium.codeium",
  "GitHub.vscode-github-actions",
  "ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers",
  # document
  "redhat.vscode-yaml",
  "richie5um2.vscode-sort-json",
  "tamasfe.even-better-toml",
  # web
  "bradlc.vscode-tailwindcss",
  "csstools.postcss",
  "dbaeumer.vscode-eslint",
  # elixir
  "JakeBecker.elixir-ls",
  "jamilabreu.vscode-phoenix-snippets",
  "msaraiva.surface",
  "phoenixframework.phoenix",
  "phoenix-liveview-snippets.phoenix-liveview-snippets",
  # dart
  "Dart-Code.dart-code",
  "Dart-Code.flutter",
  # nasm
  "13xforever.language-x86-64-assembly",
  "ms-vscode.makefile-tools",
  # kotlin
  "VisualStudioExptTeam.vscodeintellicode",
  "redhat.java",
  "vscjava.vscode-java-debug",
  "vscjava.vscode-java-test",
  "vscjava.vscode-java-dependency",
  "vscjava.vscode-gradle",
  "mathiasfrohlich.Kotlin",
  "vscjava.vscode-spring-initializr",
  "vmware.vscode-spring-boot",
  "vscjava.vscode-spring-boot-dashboard",
  #rust
  "rust-lang.rust-analyzer",
  "a5huynh.vscode-ron",
]
