recommendations = [
  # nix
  "bbenoist.Nix",
  "jnoortheen.nix-ide",
  # dev
  "eamodio.gitlens",
  "GitHub.copilot",
  "ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers",
  # config
  "PascalReitermann93.vscode-yaml-sort",
  "richie5um2.vscode-sort-json",
  "tamasfe.even-better-toml",
  # web
  "bradlc.vscode-tailwindcss",
  "dbaeumer.vscode-eslint",
  # elixir
  "JakeBecker.elixir-ls",
  "jamilabreu.vscode-phoenix-snippets",
  "msaraiva.surface",
  "phoenixframework.phoenix",
  "phoenix-liveview-snippets.phoenix-liveview-snippets",
  # dart
  "Dart-Code.dart-code",
  "Dart-Code.flutter",
  # nasm
  "13xforever.language-x86-64-assembly",
  "ms-vscode.makefile-tools",
]
